//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hubo {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hubo.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Break.
        /// </summary>
        public static string AddBreak {
            get {
                return ResourceManager.GetString("AddBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shift.
        /// </summary>
        public static string AddShiftText {
            get {
                return ResourceManager.GetString("AddShiftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vehicle.
        /// </summary>
        public static string AddVehicleText {
            get {
                return ResourceManager.GetString("AddVehicleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question #.
        /// </summary>
        public static string ChecklistQuestionNumber {
            get {
                return ResourceManager.GetString("ChecklistQuestionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a vehicle to edit..
        /// </summary>
        public static string ChooseVehicleToEdit {
            get {
                return ResourceManager.GetString("ChooseVehicleToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company: .
        /// </summary>
        public static string CompanyText {
            get {
                return ResourceManager.GetString("CompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DisplayAlertOkay {
            get {
                return ResourceManager.GetString("DisplayAlertOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string DisplayAlertTitle {
            get {
                return ResourceManager.GetString("DisplayAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Shift.
        /// </summary>
        public static string EditShift {
            get {
                return ResourceManager.GetString("EditShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Vehicle.
        /// </summary>
        public static string EditVehicleText {
            get {
                return ResourceManager.GetString("EditVehicleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Break.
        /// </summary>
        public static string EndBreak {
            get {
                return ResourceManager.GetString("EndBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsements.
        /// </summary>
        public static string Endorsements {
            get {
                return ResourceManager.GetString("Endorsements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Shift.
        /// </summary>
        public static string EndShift {
            get {
                return ResourceManager.GetString("EndShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        /// </summary>
        public static string ExportDisclaimer {
            get {
                return ResourceManager.GetString("ExportDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryText {
            get {
                return ResourceManager.GetString("HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out a valid email address..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Number.
        /// </summary>
        public static string LicenseNumber {
            get {
                return ResourceManager.GetString("LicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Version.
        /// </summary>
        public static string LicenseVersion {
            get {
                return ResourceManager.GetString("LicenseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make: .
        /// </summary>
        public static string MakeText {
            get {
                return ResourceManager.GetString("MakeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all the fields..
        /// </summary>
        public static string MissingText {
            get {
                return ResourceManager.GetString("MissingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model: .
        /// </summary>
        public static string ModelText {
            get {
                return ResourceManager.GetString("ModelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide both Username &amp; Password.
        /// </summary>
        public static string NoUsernameOrPasswordMessage {
            get {
                return ResourceManager.GetString("NoUsernameOrPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string NoUsernameOrPasswordTitle {
            get {
                return ResourceManager.GetString("NoUsernameOrPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        public static string NZTAButtonText {
            get {
                return ResourceManager.GetString("NZTAButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *PLACEHOLDER FOR DISCLAIMER*.
        /// </summary>
        public static string NZTADisclaimer {
            get {
                return ResourceManager.GetString("NZTADisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileText {
            get {
                return ResourceManager.GetString("ProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful!.
        /// </summary>
        public static string RegisterSuccessText {
            get {
                return ResourceManager.GetString("RegisterSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string RegisterSuccessTitle {
            get {
                return ResourceManager.GetString("RegisterSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration: .
        /// </summary>
        public static string RegistrationText {
            get {
                return ResourceManager.GetString("RegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Vehicles.
        /// </summary>
        public static string SearchVehiclesPlaceholder {
            get {
                return ResourceManager.GetString("SearchVehiclesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOutText {
            get {
                return ResourceManager.GetString("SignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Break.
        /// </summary>
        public static string StartBreak {
            get {
                return ResourceManager.GetString("StartBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Shift.
        /// </summary>
        public static string StartShift {
            get {
                return ResourceManager.GetString("StartShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string SwitchTextActive {
            get {
                return ResourceManager.GetString("SwitchTextActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string SwitchTextInActive {
            get {
                return ResourceManager.GetString("SwitchTextInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue logging in..
        /// </summary>
        public static string UnsuccessfulLogin {
            get {
                return ResourceManager.GetString("UnsuccessfulLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string VehiclesText {
            get {
                return ResourceManager.GetString("VehiclesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Hubo.
        /// </summary>
        public static string WelcomeEntry {
            get {
                return ResourceManager.GetString("WelcomeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
