// Sqlite.idl : IDL source for Sqlite
//

// This file will be processed by the MIDL tool to
// produce the type library (Sqlite.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(6FE9E31E-9CEB-454E-BB91-46547F1FDBB7),
	version(1.0),
]
library SqliteLib
{
	importlib("stdole2.tlb");
};

