//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hubo {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hubo.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE END BREAKS BEFORE ENDING SHIFT!.
        /// </summary>
        internal static string ActiveBreaks {
            get {
                return ResourceManager.GetString("ActiveBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Break.
        /// </summary>
        internal static string AddBreak {
            get {
                return ResourceManager.GetString("AddBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Break or Note?.
        /// </summary>
        internal static string AddBreakNote {
            get {
                return ResourceManager.GetString("AddBreakNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Drive Shift.
        /// </summary>
        internal static string AddDrive {
            get {
                return ResourceManager.GetString("AddDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shift.
        /// </summary>
        internal static string AddShiftText {
            get {
                return ResourceManager.GetString("AddShiftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vehicle.
        /// </summary>
        internal static string AddVehicleText {
            get {
                return ResourceManager.GetString("AddVehicleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        internal static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add break!.
        /// </summary>
        internal static string BreakAddError {
            get {
                return ResourceManager.GetString("BreakAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks.
        /// </summary>
        internal static string BreaksText {
            get {
                return ResourceManager.GetString("BreaksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question #.
        /// </summary>
        internal static string ChecklistQuestionNumber {
            get {
                return ResourceManager.GetString("ChecklistQuestionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a vehicle to edit..
        /// </summary>
        internal static string ChooseVehicleToEdit {
            get {
                return ResourceManager.GetString("ChooseVehicleToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string CityText {
            get {
                return ResourceManager.GetString("CityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company: .
        /// </summary>
        internal static string CompanyText {
            get {
                return ResourceManager.GetString("CompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string CountryText {
            get {
                return ResourceManager.GetString("CountryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        internal static string DateEquals {
            get {
                return ResourceManager.GetString("DateEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string DisplayAlertOkay {
            get {
                return ResourceManager.GetString("DisplayAlertOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string DisplayAlertTitle {
            get {
                return ResourceManager.GetString("DisplayAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Show Again.
        /// </summary>
        internal static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        internal static string Drive {
            get {
                return ResourceManager.GetString("Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Shift.
        /// </summary>
        internal static string DriveText {
            get {
                return ResourceManager.GetString("DriveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Breaks.
        /// </summary>
        internal static string EditBreaks {
            get {
                return ResourceManager.GetString("EditBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Notes.
        /// </summary>
        internal static string EditNotes {
            get {
                return ResourceManager.GetString("EditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Shift.
        /// </summary>
        internal static string EditShift {
            get {
                return ResourceManager.GetString("EditShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Vehicle.
        /// </summary>
        internal static string EditVehicleText {
            get {
                return ResourceManager.GetString("EditVehicleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the note section.
        /// </summary>
        internal static string EmptyNote {
            get {
                return ResourceManager.GetString("EmptyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Break.
        /// </summary>
        internal static string EndBreak {
            get {
                return ResourceManager.GetString("EndBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Hubo:.
        /// </summary>
        internal static string EndHubo {
            get {
                return ResourceManager.GetString("EndHubo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Location: .
        /// </summary>
        internal static string EndLocation {
            get {
                return ResourceManager.GetString("EndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Note: .
        /// </summary>
        internal static string EndNote {
            get {
                return ResourceManager.GetString("EndNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsements:.
        /// </summary>
        internal static string Endorsements {
            get {
                return ResourceManager.GetString("Endorsements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Shift.
        /// </summary>
        internal static string EndShift {
            get {
                return ResourceManager.GetString("EndShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        /// </summary>
        internal static string EndShiftDisclaimer {
            get {
                return ResourceManager.GetString("EndShiftDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time: .
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNABLE TO END SHIFT!.
        /// </summary>
        internal static string ErrorEndShift {
            get {
                return ResourceManager.GetString("ErrorEndShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE THAN ONE USER LOGGED IN, LOGGIN ALL USERS OUT!.
        /// </summary>
        internal static string ErrorMoreOneUser {
            get {
                return ResourceManager.GetString("ErrorMoreOneUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        /// </summary>
        internal static string ExportDisclaimer {
            get {
                return ResourceManager.GetString("ExportDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Number:.
        /// </summary>
        internal static string FleetText {
            get {
                return ResourceManager.GetString("FleetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 24 hours since last shift.
        /// </summary>
        internal static string FullyRested {
            get {
                return ResourceManager.GetString("FullyRested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUnable to Get User Details.
        /// </summary>
        internal static string GetDetailsError {
            get {
                return ResourceManager.GetString("GetDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR GETTING ONE VEHICLE!.
        /// </summary>
        internal static string GetMoreOneVehicle {
            get {
                return ResourceManager.GetString("GetMoreOneVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got It.
        /// </summary>
        internal static string GotIt {
            get {
                return ResourceManager.GetString("GotIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryText {
            get {
                return ResourceManager.GetString("HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting a date will enable you to edit/export the selected date and its past week of shifts.
        /// </summary>
        internal static string HistoryTip {
            get {
                return ResourceManager.GetString("HistoryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /70 Hours Total.
        /// </summary>
        internal static string HoursTotalText {
            get {
                return ResourceManager.GetString("HoursTotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo.
        /// </summary>
        internal static string Hubo {
            get {
                return ResourceManager.GetString("Hubo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo End: .
        /// </summary>
        internal static string HuboEnd {
            get {
                return ResourceManager.GetString("HuboEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo: .
        /// </summary>
        internal static string HuboEquals {
            get {
                return ResourceManager.GetString("HuboEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo (Not Required).
        /// </summary>
        internal static string HuboNotRequired {
            get {
                return ResourceManager.GetString("HuboNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo Start: .
        /// </summary>
        internal static string HuboStart {
            get {
                return ResourceManager.GetString("HuboStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a location.
        /// </summary>
        internal static string InputLocation {
            get {
                return ResourceManager.GetString("InputLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out a valid email address..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid reading.
        /// </summary>
        internal static string InvalidHubo {
            get {
                return ResourceManager.GetString("InvalidHubo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /24 Hours since last shift end.
        /// </summary>
        internal static string LastShiftEndText {
            get {
                return ResourceManager.GetString("LastShiftEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Number:.
        /// </summary>
        internal static string LicenseNumber {
            get {
                return ResourceManager.GetString("LicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Version:.
        /// </summary>
        internal static string LicenseVersion {
            get {
                return ResourceManager.GetString("LicenseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: .
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates:.
        /// </summary>
        internal static string LocationGeo {
            get {
                return ResourceManager.GetString("LocationGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to log out?.
        /// </summary>
        internal static string LogOutMessage {
            get {
                return ResourceManager.GetString("LogOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make and Model: .
        /// </summary>
        internal static string MakeModelText {
            get {
                return ResourceManager.GetString("MakeModelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all the fields..
        /// </summary>
        internal static string MissingText {
            get {
                return ResourceManager.GetString("MissingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE THAN ONE ACTIVE BREAK DISCOVERED!.
        /// </summary>
        internal static string MoreOneActiveBreak {
            get {
                return ResourceManager.GetString("MoreOneActiveBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE THAN ONE ACTIVE DRIVE SHIFTS DISCOVERED!.
        /// </summary>
        internal static string MoreOneActiveDrive {
            get {
                return ResourceManager.GetString("MoreOneActiveDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE THAN ONE ACTIVE SHIFT DISCOVERED!.
        /// </summary>
        internal static string MoreOneActiveShift {
            get {
                return ResourceManager.GetString("MoreOneActiveShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE THAN ONE ACTIVE VEHICLE DETECTED!.
        /// </summary>
        internal static string MoreOneActiveVehicle {
            get {
                return ResourceManager.GetString("MoreOneActiveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ACTIVE DRIVE SHIFTS.
        /// </summary>
        internal static string NoActiveDrives {
            get {
                return ResourceManager.GetString("NoActiveDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ACTIVE SHIFTS.
        /// </summary>
        internal static string NoActiveShifts {
            get {
                return ResourceManager.GetString("NoActiveShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active vehicle has been set..
        /// </summary>
        internal static string NoActiveVehicle {
            get {
                return ResourceManager.GetString("NoActiveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE SELECT A VEHICLE BEFORE ENDING YOUR SHIFT.
        /// </summary>
        internal static string NoActiveVehicles {
            get {
                return ResourceManager.GetString("NoActiveVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shifts have been recorded yet.
        /// </summary>
        internal static string NoShiftsDoneYet {
            get {
                return ResourceManager.GetString("NoShiftsDoneYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shifts found for the last 24 hours.
        /// </summary>
        internal static string NoShiftsFound {
            get {
                return ResourceManager.GetString("NoShiftsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: .
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add note!.
        /// </summary>
        internal static string NoteAddError {
            get {
                return ResourceManager.GetString("NoteAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NotesText {
            get {
                return ResourceManager.GetString("NotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteText {
            get {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide both Username &amp; Password.
        /// </summary>
        internal static string NoUsernameOrPasswordMessage {
            get {
                return ResourceManager.GetString("NoUsernameOrPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string NoUsernameOrPasswordTitle {
            get {
                return ResourceManager.GetString("NoUsernameOrPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NZTA.
        /// </summary>
        internal static string NZTA {
            get {
                return ResourceManager.GetString("NZTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string NZTAButtonText {
            get {
                return ResourceManager.GetString("NZTAButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *PLACEHOLDER FOR DISCLAIMER*.
        /// </summary>
        internal static string NZTADisclaimer {
            get {
                return ResourceManager.GetString("NZTADisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other....
        /// </summary>
        internal static string OthersText {
            get {
                return ResourceManager.GetString("OthersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostCode:.
        /// </summary>
        internal static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileText {
            get {
                return ResourceManager.GetString("ProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful!.
        /// </summary>
        internal static string RegisterSuccessText {
            get {
                return ResourceManager.GetString("RegisterSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RegisterSuccessTitle {
            get {
                return ResourceManager.GetString("RegisterSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration: .
        /// </summary>
        internal static string RegistrationText {
            get {
                return ResourceManager.GetString("RegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Vehicles.
        /// </summary>
        internal static string SearchVehiclesPlaceholder {
            get {
                return ResourceManager.GetString("SearchVehiclesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a shift.
        /// </summary>
        internal static string SelectAShift {
            get {
                return ResourceManager.GetString("SelectAShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select A Vehicle.
        /// </summary>
        internal static string SelectAVehicle {
            get {
                return ResourceManager.GetString("SelectAVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a break period.
        /// </summary>
        internal static string SelectBreak {
            get {
                return ResourceManager.GetString("SelectBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a note.
        /// </summary>
        internal static string SelectNote {
            get {
                return ResourceManager.GetString("SelectNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a vehicle.
        /// </summary>
        internal static string SelectVehicle {
            get {
                return ResourceManager.GetString("SelectVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift:.
        /// </summary>
        internal static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save shift!.
        /// </summary>
        internal static string ShiftAddError {
            get {
                return ResourceManager.GetString("ShiftAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift End Time.
        /// </summary>
        internal static string ShiftEndTime {
            get {
                return ResourceManager.GetString("ShiftEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a shift.
        /// </summary>
        internal static string ShiftPickerTitle {
            get {
                return ResourceManager.GetString("ShiftPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Start Time.
        /// </summary>
        internal static string ShiftStartTime {
            get {
                return ResourceManager.GetString("ShiftStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOutText {
            get {
                return ResourceManager.GetString("SignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Break.
        /// </summary>
        internal static string StartBreak {
            get {
                return ResourceManager.GetString("StartBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Driving.
        /// </summary>
        internal static string StartDriving {
            get {
                return ResourceManager.GetString("StartDriving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Hubo:.
        /// </summary>
        internal static string StartHubo {
            get {
                return ResourceManager.GetString("StartHubo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Location: .
        /// </summary>
        internal static string StartLocation {
            get {
                return ResourceManager.GetString("StartLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Note: .
        /// </summary>
        internal static string StartNote {
            get {
                return ResourceManager.GetString("StartNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Shift.
        /// </summary>
        internal static string StartShift {
            get {
                return ResourceManager.GetString("StartShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time: .
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Driving.
        /// </summary>
        internal static string StopDriving {
            get {
                return ResourceManager.GetString("StopDriving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop using vehicle.
        /// </summary>
        internal static string StopUsingVehicle {
            get {
                return ResourceManager.GetString("StopUsingVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surburb:.
        /// </summary>
        internal static string SuburbText {
            get {
                return ResourceManager.GetString("SuburbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string SwitchTextActive {
            get {
                return ResourceManager.GetString("SwitchTextActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string SwitchTextInActive {
            get {
                return ResourceManager.GetString("SwitchTextInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        internal static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNABLE TO GET ACTIVE BREAK!.
        /// </summary>
        internal static string UnableToGetBreak {
            get {
                return ResourceManager.GetString("UnableToGetBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNABLE TO GET CURRENT SHIFT!.
        /// </summary>
        internal static string UnableToGetShift {
            get {
                return ResourceManager.GetString("UnableToGetShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANNOT RETRIEVE VEHICLE IN USE!.
        /// </summary>
        internal static string UnableToGetVehicle {
            get {
                return ResourceManager.GetString("UnableToGetVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue logging in..
        /// </summary>
        internal static string UnsuccessfulLogin {
            get {
                return ResourceManager.GetString("UnsuccessfulLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName:.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Vehicle.
        /// </summary>
        internal static string UseVehicle {
            get {
                return ResourceManager.GetString("UseVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        internal static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        internal static string VehiclesText {
            get {
                return ResourceManager.GetString("VehiclesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Hubo.
        /// </summary>
        internal static string WelcomeEntry {
            get {
                return ResourceManager.GetString("WelcomeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
